# compose\docker-compose.dev.yml
name: adv-store-dev-django-react
services:
  db:
    image: postgres:15-alpine
    env_file:
      - ../envs/.env.dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:${PGDB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$PGDB_USER -d $$PGDB_NAME"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8.0.2-alpine
    volumes:
      - redis_data_dev:/data
    # ports:
    #   - "127.0.0.1:6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile.dev
    env_file:
      - ../envs/.env.dev
    volumes:
      - ../backend:/usr/src/app
    working_dir: /usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile.dev
    env_file:
      - ../envs/.env.dev
    environment:
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ../frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    # command: sh -lc "npm install && npm run dev -- --hostname 0.0.0.0 --port 3000" # every restart container, npm reinstall again
    # command: sh -lc "npm run dev -- --hostname 0.0.0.0 --port 3000"
    # command: sh -lc "test -d node_modules && npm run dev -- --hostname 0.0.0.0 --port 3000 || (npm install && npm run dev -- --hostname 0.0.0.0 --port 3000)"
    command: sh -lc "test -f node_modules/.bin/next || npm install; npm run dev -- --hostname 0.0.0.0 --port 3000"

    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data_dev:
    external : true
  redis_data_dev:
  frontend_node_modules:
